'use client';

import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
  pdf,
} from '@react-pdf/renderer';
import { computeFreeboard } from '@/engine/freeboard';
import type {
  CrossSectionPoint,
  BridgeGeometry,
  FlowProfile,
  Coefficients,
  CalculationResults,
  HecRasComparison,
} from '@/engine/types';
import type { AiSummaryResponse } from '@/lib/api/ai-summary-prompt';
import { captureCharts, CapturedChart } from './pdf-chart-capture';

/* ─── Constants ─── */

const METHODS = ['energy', 'momentum', 'yarnell', 'wspro'] as const;
const METHOD_LABELS: Record<string, string> = {
  energy: 'Energy',
  momentum: 'Momentum',
  yarnell: 'Yarnell',
  wspro: 'WSPRO',
};

const C = {
  primary: '#1e40af',
  text: '#111827',
  textLight: '#6b7280',
  textMuted: '#9ca3af',
  border: '#e5e7eb',
  borderLight: '#f3f4f6',
  green: '#15803d',
  amber: '#b45309',
  red: '#dc2626',
  white: '#ffffff',
  bg: '#f9fafb',
};

/* ─── Styles ─── */

const s = StyleSheet.create({
  /* Page */
  page: {
    paddingTop: 40,
    paddingBottom: 45,
    paddingHorizontal: 42,
    fontFamily: 'Helvetica',
    fontSize: 9,
    color: C.text,
  },
  pageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    borderBottomWidth: 0.5,
    borderBottomColor: C.border,
    paddingBottom: 4,
    marginBottom: 10,
  },
  pageHeaderLeft: { fontSize: 8, color: C.textMuted, letterSpacing: 0.5 },
  pageHeaderRight: { fontSize: 8, color: C.textLight, fontFamily: 'Helvetica-Bold' },
  pageFooter: {
    position: 'absolute',
    bottom: 20,
    left: 42,
    right: 42,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 0.5,
    borderTopColor: C.borderLight,
    paddingTop: 3,
  },
  footerText: { fontSize: 7, color: C.textMuted },

  /* Cover */
  coverCenter: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  coverRule: { width: 60, height: 2, backgroundColor: C.primary, marginBottom: 24 },
  coverTitle: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: C.text, textAlign: 'center' },
  coverSub: { fontSize: 12, color: C.textLight, marginTop: 4, textAlign: 'center' },
  coverRuleB: { width: 60, height: 2, backgroundColor: C.primary, marginTop: 24, marginBottom: 16 },
  coverDate: { fontSize: 10, color: C.textMuted },

  /* Sections */
  section: { marginBottom: 12 },
  sectionTitle: { fontSize: 11, fontFamily: 'Helvetica-Bold', color: C.text, marginBottom: 2 },
  sectionDesc: { fontSize: 7.5, color: C.textMuted, marginBottom: 6, maxWidth: 420 },
  divider: { borderBottomWidth: 0.5, borderBottomColor: C.border, marginTop: 4, marginBottom: 10 },
  subTitle: { fontSize: 9, fontFamily: 'Helvetica-Bold', color: '#374151', marginTop: 6, marginBottom: 3 },
  subDesc: { fontSize: 7, color: C.textMuted, marginBottom: 3 },

  /* Key-Value grid */
  kvGrid: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 6 },
  kvItem: { width: '33%', flexDirection: 'row', marginBottom: 2 },
  kvLabel: { fontSize: 8, color: C.textLight },
  kvValue: { fontSize: 8, fontFamily: 'Helvetica-Bold', marginLeft: 3 },

  /* Tables */
  table: { borderWidth: 0.5, borderColor: C.border, marginBottom: 4 },
  tHead: { flexDirection: 'row', backgroundColor: C.borderLight, borderBottomWidth: 0.5, borderBottomColor: C.border },
  tRow: { flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: C.border },
  tRowAlt: { flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: C.border, backgroundColor: C.bg },
  th: { fontSize: 7.5, fontFamily: 'Helvetica-Bold', paddingVertical: 2.5, paddingHorizontal: 4 },
  td: { fontSize: 7.5, paddingVertical: 2, paddingHorizontal: 4 },
  tdR: { fontSize: 7.5, paddingVertical: 2, paddingHorizontal: 4, textAlign: 'right' },

  /* Charts */
  chartWrap: { marginBottom: 8 },
  chartLabel: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: '#374151', marginBottom: 3 },
  chartImg: { width: '100%', objectFit: 'contain' },
  chartBorder: { borderWidth: 0.5, borderColor: C.border, borderRadius: 2, overflow: 'hidden', backgroundColor: C.white },

  /* Bullets */
  bulletItem: { flexDirection: 'row', marginBottom: 2, paddingRight: 16 },
  bulletDot: { fontSize: 8, color: C.textMuted, marginRight: 4, width: 8 },
  bulletText: { fontSize: 8, color: C.textLight, flex: 1 },
});

/* ─── Helpers ─── */

function PageHeader({ reportTitle }: { reportTitle: string }) {
  return (
    <View style={s.pageHeader} fixed>
      <Text style={s.pageHeaderLeft}>{reportTitle.toUpperCase()}</Text>
      <Text style={s.pageHeaderRight}>Hydraulic Loss Assessment</Text>
    </View>
  );
}

function PageFooter({ date }: { date: string }) {
  return (
    <View style={s.pageFooter} fixed>
      <Text style={s.footerText}>Generated by Bridge Loss Calculator · QA verification only</Text>
      <Text style={s.footerText} render={({ pageNumber, totalPages }) => `${date} · Page ${pageNumber} of ${totalPages}`} />
    </View>
  );
}

function Sec({ num, title, desc, children }: { num: number; title: string; desc?: string; children: React.ReactNode }) {
  return (
    <View style={s.section}>
      <Text style={s.sectionTitle}>{num}. {title}</Text>
      {desc ? <Text style={s.sectionDesc}>{desc}</Text> : null}
      {children}
    </View>
  );
}

function Divider() {
  return <View style={s.divider} />;
}

function KV({ label, value }: { label: string; value: string | number }) {
  return (
    <View style={s.kvItem}>
      <Text style={s.kvLabel}>{label}:</Text>
      <Text style={s.kvValue}>{String(value)}</Text>
    </View>
  );
}

function Bullet({ text, color }: { text: string; color?: string }) {
  return (
    <View style={s.bulletItem} wrap={false}>
      <Text style={s.bulletDot}>•</Text>
      <Text style={[s.bulletText, color ? { color } : {}]}>{text}</Text>
    </View>
  );
}

/* ─── Table ─── */

interface Col {
  header: string;
  width: string | number;
  align?: 'left' | 'right' | 'center';
  render: (row: Record<string, unknown>, i: number) => string;
  cellStyle?: (row: Record<string, unknown>) => object | undefined;
}

function DataTable({ columns, data }: { columns: Col[]; data: Record<string, unknown>[] }) {
  return (
    <View style={s.table}>
      <View style={s.tHead} fixed>
        {columns.map((col, ci) => (
          <Text key={ci} style={[s.th, { width: col.width, textAlign: col.align || 'left' }]}>
            {col.header}
          </Text>
        ))}
      </View>
      {data.map((row, ri) => (
        <View key={ri} style={ri % 2 ? s.tRowAlt : s.tRow} wrap={false}>
          {columns.map((col, ci) => (
            <Text key={ci} style={[
              col.align === 'right' ? s.tdR : s.td,
              { width: col.width, textAlign: col.align || 'left' },
              (col.cellStyle?.(row) || {}) as Record<string, string | number>,
            ]}>
              {col.render(row, ri)}
            </Text>
          ))}
        </View>
      ))}
    </View>
  );
}

/* ─── Report data ─── */

export interface PdfReportData {
  projectName: string;
  crossSection: CrossSectionPoint[];
  bridge: BridgeGeometry;
  profiles: FlowProfile[];
  coefficients: Coefficients;
  results: CalculationResults | null;
  hecRasComparison: HecRasComparison[];
  aiSummary: AiSummaryResponse | null;
  charts: CapturedChart[];
}

/* ─── Document ─── */

function ReportDocument({ data }: { data: PdfReportData }) {
  const { projectName, crossSection, bridge, profiles, coefficients, results, hecRasComparison, aiSummary, charts } = data;
  const date = new Date().toLocaleDateString('en-AU', { year: 'numeric', month: 'long', day: 'numeric' });
  const title = projectName || 'Bridge Hydraulic Loss Assessment';
  const freeboard = results ? computeFreeboard(results, bridge, profiles, coefficients.freeboardThreshold) : null;
  const xsChart = charts.find((c) => c.id === 'cross-section');
  const otherCharts = charts.filter((c) => c.id !== 'cross-section');
  const hasHecRas = hecRasComparison.length > 0 && hecRasComparison.some((c) => c.upstreamWsel !== null || c.headLoss !== null);

  let sn = 0;
  const next = () => ++sn;

  return (
    <Document title={`${title} - Report`} author="Bridge Loss Calculator">

      {/* ═══ COVER ═══ */}
      <Page size="A4" style={[s.page, { paddingTop: 0, paddingBottom: 0 }]}>
        <View style={s.coverCenter}>
          <View style={s.coverRule} />
          <Text style={s.coverTitle}>Bridge Hydraulic Loss Assessment</Text>
          {projectName ? <Text style={s.coverSub}>{projectName}</Text> : null}
          <View style={s.coverRuleB} />
          <Text style={s.coverDate}>{date}</Text>
        </View>
      </Page>

      {/* ═══ BODY — single flowing page ═══ */}
      <Page size="A4" style={s.page} wrap>
        <PageHeader reportTitle={title} />
        <PageFooter date={date} />

        {/* ── 1. Input Summary ── */}
        <Sec num={next()} title="Input Summary" desc="Summary of bridge geometry, coefficients, and flow profiles used as inputs.">
          <Text style={s.subTitle}>Bridge Geometry</Text>
          <View style={s.kvGrid}>
            <KV label="Low Chord Left" value={bridge.lowChordLeft} />
            <KV label="Low Chord Right" value={bridge.lowChordRight} />
            <KV label="High Chord" value={bridge.highChord} />
            <KV label="Skew Angle" value={`${bridge.skewAngle}°`} />
            <KV label="Left Abutment" value={bridge.leftAbutmentStation} />
            <KV label="Right Abutment" value={bridge.rightAbutmentStation} />
            <KV label="Piers" value={bridge.piers.length} />
            {coefficients.debrisBlockagePct > 0 ? <KV label="Debris Blockage" value={`${coefficients.debrisBlockagePct}%`} /> : null}
          </View>

          <Text style={s.subTitle}>Coefficients</Text>
          <View style={s.kvGrid}>
            <KV label="Contraction" value={coefficients.contractionCoeff} />
            <KV label="Expansion" value={coefficients.expansionCoeff} />
            {coefficients.yarnellK !== null ? <KV label="Yarnell K" value={coefficients.yarnellK} /> : null}
            <KV label="Max Iterations" value={coefficients.maxIterations} />
            <KV label="Tolerance" value={coefficients.tolerance} />
            {coefficients.manningsNSensitivityPct !== null && coefficients.manningsNSensitivityPct > 0
              ? <KV label="Manning's n Sensitivity" value={`±${coefficients.manningsNSensitivityPct}%`} />
              : null}
          </View>

          <Text style={s.subTitle}>Flow Profiles</Text>
          <DataTable
            columns={[
              { header: 'Name', width: '25%', render: (r) => r.name as string },
              { header: 'ARI', width: '15%', render: (r) => (r.ari as string) || '—' },
              { header: 'Q', width: '20%', align: 'right', render: (r) => String(r.discharge) },
              { header: 'DS WSEL', width: '20%', align: 'right', render: (r) => String(r.dsWsel) },
              { header: 'Slope', width: '20%', align: 'right', render: (r) => String(r.channelSlope) },
            ]}
            data={profiles as unknown as Record<string, unknown>[]}
          />
        </Sec>

        {/* ── Cross-Section Chart ── */}
        {xsChart ? (
          <View wrap={false}>
            <Divider />
            <View style={s.chartWrap}>
              <Text style={s.chartLabel}>Cross-Section Profile</Text>
              <View style={s.chartBorder}>
                <Image style={s.chartImg} src={xsChart.dataUrl} />
              </View>
            </View>
          </View>
        ) : null}

        <Divider />

        {/* ── 2. Cross-Section Data ── */}
        <Sec num={next()} title="Cross-Section Data" desc={`Surveyed channel geometry (${crossSection.length} points).`}>
          <DataTable
            columns={[
              { header: 'Station', width: '25%', align: 'right', render: (r) => (r.station as number).toFixed(1) },
              { header: 'Elevation', width: '25%', align: 'right', render: (r) => (r.elevation as number).toFixed(2) },
              { header: "Manning's n", width: '25%', align: 'right', render: (r) => String(r.manningsN) },
              { header: 'Bank', width: '25%', render: (r) => (r.bankStation as string) || '—' },
            ]}
            data={crossSection as unknown as Record<string, unknown>[]}
          />
        </Sec>

        {/* ── 3. Freeboard Check ── */}
        {results && freeboard ? (
          <>
            <Divider />
            <Sec num={next()} title="Freeboard Check" desc="Clearance between computed upstream WSEL (worst across methods) and bridge low chord. Positive = clearance. Negative = pressure/overtopping.">
              <DataTable
                columns={[
                  { header: 'Profile', width: '16%', render: (r) => r.profileName as string },
                  { header: 'ARI', width: '10%', render: (r) => (r.ari as string) || '—' },
                  { header: 'Q', width: '12%', align: 'right', render: (r) => (r.discharge as number).toFixed(0) },
                  { header: 'US WSEL', width: '14%', align: 'right', render: (r) => (r.usWsel as number).toFixed(2) },
                  { header: 'Low Chord', width: '14%', align: 'right', render: (r) => (r.lowChord as number).toFixed(2) },
                  { header: 'Freeboard', width: '14%', align: 'right', render: (r) => (r.freeboard as number).toFixed(2) },
                  {
                    header: 'Status', width: '20%', align: 'center',
                    render: (r) => (r.status as string).toUpperCase(),
                    cellStyle: (r) => ({
                      fontFamily: 'Helvetica-Bold',
                      color: (r.status as string) === 'clear' ? C.green : (r.status as string) === 'low' ? C.amber : C.red,
                    }),
                  },
                ]}
                data={freeboard.profiles as unknown as Record<string, unknown>[]}
              />
              {freeboard.zeroFreeboardQ !== null ? (
                <Text style={{ fontSize: 7, color: C.textLight, marginTop: 2 }}>
                  Estimated Q at zero freeboard: {freeboard.zeroFreeboardQ.toFixed(0)} (interpolated)
                </Text>
              ) : null}
            </Sec>
          </>
        ) : null}

        {/* ── 4. Flow Regime ── */}
        {results ? (
          <>
            <Divider />
            <Sec num={next()} title="Flow Regime" desc="F = Free Surface, P = Pressure, O = Overtopping. Yarnell is valid for free-surface only — flagged (!) otherwise.">
              <View style={s.table}>
                <View style={s.tHead} fixed>
                  <Text style={[s.th, { width: '20%' }]}>Method</Text>
                  {profiles.map((p) => (
                    <Text key={p.name} style={[s.th, { width: `${80 / profiles.length}%`, textAlign: 'center' }]}>{p.name}</Text>
                  ))}
                </View>
                {METHODS.map((m, mi) => (
                  <View key={m} style={mi % 2 ? s.tRowAlt : s.tRow} wrap={false}>
                    <Text style={[s.td, { width: '20%', fontFamily: 'Helvetica-Bold' }]}>{METHOD_LABELS[m]}</Text>
                    {results[m].map((r, i) => {
                      const lbl = r.flowRegime === 'free-surface' ? 'F' : r.flowRegime === 'pressure' ? 'P' : 'O';
                      const warn = m === 'yarnell' && r.flowRegime !== 'free-surface';
                      return (
                        <Text key={i} style={[
                          s.td, { width: `${80 / profiles.length}%`, textAlign: 'center' },
                          warn ? { color: C.amber, fontFamily: 'Helvetica-Bold' } : {},
                        ]}>
                          {lbl}{warn ? ' (!)' : ''}
                        </Text>
                      );
                    })}
                  </View>
                ))}
              </View>
            </Sec>
          </>
        ) : null}

        {/* ── 5. Method Comparison ── */}
        {results ? (
          <>
            <Divider />
            <Sec num={next()} title="Method Comparison" desc="Four independent methods compared. Consistent results increase confidence; divergence >10% warrants investigation.">
              {([
                { t: 'Upstream WSEL', k: 'upstreamWsel' as const, d: 2 },
                { t: 'Head Loss (Afflux)', k: 'totalHeadLoss' as const, d: 3 },
                { t: 'Approach Velocity', k: 'approachVelocity' as const, d: 2 },
                { t: 'Froude Number', k: 'froudeApproach' as const, d: 3 },
              ] as const).map(({ t, k, d }) => (
                <View key={t} style={{ marginBottom: 6 }} wrap={false}>
                  <Text style={{ fontSize: 8, fontFamily: 'Helvetica-Bold', color: '#374151', marginBottom: 2 }}>{t}</Text>
                  <View style={s.table}>
                    <View style={s.tHead}>
                      <Text style={[s.th, { width: '20%' }]}>Method</Text>
                      {profiles.map((p) => (
                        <Text key={p.name} style={[s.th, { width: `${80 / profiles.length}%`, textAlign: 'right' }]}>{p.name}</Text>
                      ))}
                    </View>
                    {METHODS.map((m, mi) => (
                      <View key={m} style={mi % 2 ? s.tRowAlt : s.tRow}>
                        <Text style={[s.td, { width: '20%', fontFamily: 'Helvetica-Bold' }]}>{METHOD_LABELS[m]}</Text>
                        {results[m].map((r, i) => (
                          <Text key={i} style={[
                            s.tdR, { width: `${80 / profiles.length}%` },
                            r.error ? { color: C.red, fontStyle: 'italic' } : {},
                          ]}>
                            {r.error ? 'ERR' : r[k].toFixed(d)}
                          </Text>
                        ))}
                      </View>
                    ))}
                  </View>
                </View>
              ))}
            </Sec>
          </>
        ) : null}

        {/* ── 6. HEC-RAS Comparison ── */}
        {hasHecRas ? (
          <>
            <Divider />
            <Sec num={next()} title="HEC-RAS Comparison" desc="Validation against HEC-RAS model results. Differences may indicate geometry or coefficient discrepancies.">
              <View style={s.table}>
                <View style={s.tHead} fixed>
                  <Text style={[s.th, { width: '20%' }]}>Profile</Text>
                  <Text style={[s.th, { width: '20%', textAlign: 'right' }]}>HEC-RAS WSEL</Text>
                  <Text style={[s.th, { width: '20%', textAlign: 'right' }]}>Energy WSEL</Text>
                  <Text style={[s.th, { width: '20%', textAlign: 'right' }]}>HEC-RAS h_L</Text>
                  <Text style={[s.th, { width: '20%', textAlign: 'right' }]}>Energy h_L</Text>
                </View>
                {hecRasComparison.map((h, i) => {
                  const energyResult = results?.energy[i];
                  return (
                    <View key={i} style={i % 2 ? s.tRowAlt : s.tRow} wrap={false}>
                      <Text style={[s.td, { width: '20%' }]}>{h.profileName}</Text>
                      <Text style={[s.tdR, { width: '20%' }]}>{h.upstreamWsel?.toFixed(2) ?? '—'}</Text>
                      <Text style={[s.tdR, { width: '20%' }]}>{energyResult && !energyResult.error ? energyResult.upstreamWsel.toFixed(2) : '—'}</Text>
                      <Text style={[s.tdR, { width: '20%' }]}>{h.headLoss?.toFixed(3) ?? '—'}</Text>
                      <Text style={[s.tdR, { width: '20%' }]}>{energyResult && !energyResult.error ? energyResult.totalHeadLoss.toFixed(3) : '—'}</Text>
                    </View>
                  );
                })}
              </View>
            </Sec>
          </>
        ) : null}

        {/* ── 7. Charts ── */}
        {otherCharts.length > 0 ? (
          <>
            <Divider />
            <Sec num={next()} title="Charts" desc="Afflux rating curve and upstream WSEL trend.">
              {otherCharts.map((chart) => (
                <View key={chart.id} style={s.chartWrap} wrap={false}>
                  <Text style={s.chartLabel}>{chart.label}</Text>
                  <View style={s.chartBorder}>
                    <Image style={s.chartImg} src={chart.dataUrl} />
                  </View>
                </View>
              ))}
            </Sec>
          </>
        ) : null}

        {/* ── 8. AI Analysis ── */}
        {aiSummary ? (
          <>
            <Divider />
            <Sec num={next()} title="AI Analysis" desc="Automated review of results. Supplementary only — engineering judgement takes precedence.">
              <Text style={s.subTitle}>Summary</Text>
              {aiSummary.overall.map((item, i) => <Bullet key={i} text={item} color="#374151" />)}

              {aiSummary.callouts.regime ? (
                <View style={{ marginTop: 4 }}>
                  <Text style={[s.subTitle, { fontSize: 8 }]}>Flow Regime</Text>
                  {aiSummary.callouts.regime.map((item, i) => <Bullet key={i} text={item} />)}
                </View>
              ) : null}

              {aiSummary.callouts.freeboard ? (
                <View style={{ marginTop: 4 }}>
                  <Text style={[s.subTitle, { fontSize: 8 }]}>Freeboard</Text>
                  {aiSummary.callouts.freeboard.map((item, i) => <Bullet key={i} text={item} />)}
                </View>
              ) : null}

              {aiSummary.callouts.comparison ? (
                <View style={{ marginTop: 4 }}>
                  <Text style={[s.subTitle, { fontSize: 8 }]}>Method Comparison</Text>
                  {aiSummary.callouts.comparison.map((item, i) => <Bullet key={i} text={item} />)}
                </View>
              ) : null}

              {aiSummary.callouts.afflux ? (
                <View style={{ marginTop: 4 }}>
                  <Text style={[s.subTitle, { fontSize: 8 }]}>Afflux Trends</Text>
                  {aiSummary.callouts.afflux.map((item, i) => <Bullet key={i} text={item} />)}
                </View>
              ) : null}

              {aiSummary.callouts.hecras ? (
                <View style={{ marginTop: 4 }}>
                  <Text style={[s.subTitle, { fontSize: 8 }]}>HEC-RAS Comparison</Text>
                  {aiSummary.callouts.hecras.map((item, i) => <Bullet key={i} text={item} />)}
                </View>
              ) : null}

              <Text style={{ fontSize: 6, color: C.textMuted, fontStyle: 'italic', marginTop: 10 }}>
                Generated by AI. For reference only — does not constitute engineering advice.
              </Text>
            </Sec>
          </>
        ) : null}

      </Page>
    </Document>
  );
}

/* ─── Public API ─── */

export async function generatePdf(data: Omit<PdfReportData, 'charts'>): Promise<void> {
  const charts = await captureCharts();
  const reportData: PdfReportData = { ...data, charts };
  const blob = await pdf(<ReportDocument data={reportData} />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const safeName = (data.projectName || 'bridge-loss-report').replace(/[^a-zA-Z0-9-_ ]/g, '').replace(/\s+/g, '-');
  a.download = `${safeName}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
