'use client';

import { useProjectStore } from '@/store/project-store';
import { computeFreeboard } from '@/engine/freeboard';

export function PrintReport() {
  const crossSection = useProjectStore((s) => s.crossSection);
  const bridge = useProjectStore((s) => s.bridgeGeometry);
  const profiles = useProjectStore((s) => s.flowProfiles);
  const coefficients = useProjectStore((s) => s.coefficients);
  const results = useProjectStore((s) => s.results);
  const projectName = useProjectStore((s) => s.projectName);

  const methods = ['energy', 'momentum', 'yarnell', 'wspro'] as const;
  const freeboard = results ? computeFreeboard(results, bridge, profiles, coefficients.freeboardThreshold) : null;

  return (
    <div className="print-report hidden print:block bg-white text-black p-8 text-sm font-sans">
      {/* Cover Page */}
      <div className="flex flex-col items-center justify-center min-h-[80vh] text-center break-after-page">
        <h1 className="text-3xl font-bold text-gray-900" style={{ fontFamily: 'Georgia, serif' }}>Bridge Hydraulic Loss Assessment</h1>
        {projectName && <h2 className="text-xl text-gray-600 mt-2" style={{ fontFamily: 'Georgia, serif' }}>{projectName}</h2>}
        <div className="w-24 h-0.5 bg-blue-600 my-8" />
        <p className="text-gray-500">{new Date().toLocaleDateString('en-AU', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        <p className="text-gray-400 text-xs mt-4">Generated by Bridge Loss Calculator</p>
      </div>

      {/* Input Summary */}
      <div className="break-before-page">
        <h2 className="text-lg font-bold border-b-2 border-blue-600 pb-1 mb-4" style={{ fontFamily: 'Georgia, serif' }}>Input Summary</h2>

        <h3 className="text-sm font-bold mt-4 mb-2">Cross-Section ({crossSection.length} points)</h3>
        <table className="w-full text-xs border-collapse">
          <thead>
            <tr className="bg-gray-100">
              <th className="border border-gray-300 px-2 py-1 text-left">Station</th>
              <th className="border border-gray-300 px-2 py-1 text-left">Elevation</th>
              <th className="border border-gray-300 px-2 py-1 text-left">Manning&apos;s n</th>
              <th className="border border-gray-300 px-2 py-1 text-left">Bank</th>
            </tr>
          </thead>
          <tbody>
            {crossSection.map((p, i) => (
              <tr key={i}>
                <td className="border border-gray-300 px-2 py-0.5 font-mono">{p.station.toFixed(1)}</td>
                <td className="border border-gray-300 px-2 py-0.5 font-mono">{p.elevation.toFixed(2)}</td>
                <td className="border border-gray-300 px-2 py-0.5 font-mono">{p.manningsN}</td>
                <td className="border border-gray-300 px-2 py-0.5">{p.bankStation ?? '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <h3 className="text-sm font-bold mt-4 mb-2">Bridge Geometry</h3>
        <div className="grid grid-cols-2 gap-x-8 gap-y-1 text-xs">
          <div>Low Chord Left: <span className="font-mono">{bridge.lowChordLeft}</span></div>
          <div>Low Chord Right: <span className="font-mono">{bridge.lowChordRight}</span></div>
          <div>High Chord: <span className="font-mono">{bridge.highChord}</span></div>
          <div>Skew Angle: <span className="font-mono">{bridge.skewAngle}&deg;</span></div>
          <div>Left Abutment: <span className="font-mono">{bridge.leftAbutmentStation}</span></div>
          <div>Right Abutment: <span className="font-mono">{bridge.rightAbutmentStation}</span></div>
          <div>Piers: <span className="font-mono">{bridge.piers.length}</span></div>
          {coefficients.debrisBlockagePct > 0 && <div>Debris Blockage: <span className="font-mono">{coefficients.debrisBlockagePct}%</span></div>}
        </div>

        <h3 className="text-sm font-bold mt-4 mb-2">Flow Profiles</h3>
        <table className="w-full text-xs border-collapse">
          <thead>
            <tr className="bg-gray-100">
              <th className="border border-gray-300 px-2 py-1 text-left">Name</th>
              <th className="border border-gray-300 px-2 py-1 text-left">ARI</th>
              <th className="border border-gray-300 px-2 py-1 text-right">Q</th>
              <th className="border border-gray-300 px-2 py-1 text-right">DS WSEL</th>
              <th className="border border-gray-300 px-2 py-1 text-right">Slope</th>
            </tr>
          </thead>
          <tbody>
            {profiles.map((p, i) => (
              <tr key={i}>
                <td className="border border-gray-300 px-2 py-0.5">{p.name}</td>
                <td className="border border-gray-300 px-2 py-0.5">{p.ari || '—'}</td>
                <td className="border border-gray-300 px-2 py-0.5 text-right font-mono">{p.discharge}</td>
                <td className="border border-gray-300 px-2 py-0.5 text-right font-mono">{p.dsWsel}</td>
                <td className="border border-gray-300 px-2 py-0.5 text-right font-mono">{p.channelSlope}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Freeboard Check */}
      {freeboard && (
        <div className="break-before-page">
          <h2 className="text-lg font-bold border-b-2 border-blue-600 pb-1 mb-4" style={{ fontFamily: 'Georgia, serif' }}>Freeboard Check</h2>
          <table className="w-full text-xs border-collapse">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-gray-300 px-2 py-1 text-left">Profile</th>
                <th className="border border-gray-300 px-2 py-1 text-left">ARI</th>
                <th className="border border-gray-300 px-2 py-1 text-right">Q</th>
                <th className="border border-gray-300 px-2 py-1 text-right">US WSEL</th>
                <th className="border border-gray-300 px-2 py-1 text-right">Low Chord</th>
                <th className="border border-gray-300 px-2 py-1 text-right">Freeboard</th>
                <th className="border border-gray-300 px-2 py-1 text-center">Status</th>
              </tr>
            </thead>
            <tbody>
              {freeboard.profiles.map((r, i) => (
                <tr key={i}>
                  <td className="border border-gray-300 px-2 py-0.5">{r.profileName}</td>
                  <td className="border border-gray-300 px-2 py-0.5">{r.ari || '—'}</td>
                  <td className="border border-gray-300 px-2 py-0.5 text-right font-mono">{r.discharge.toFixed(0)}</td>
                  <td className="border border-gray-300 px-2 py-0.5 text-right font-mono">{r.usWsel.toFixed(2)}</td>
                  <td className="border border-gray-300 px-2 py-0.5 text-right font-mono">{r.lowChord.toFixed(2)}</td>
                  <td className="border border-gray-300 px-2 py-0.5 text-right font-mono">{r.freeboard.toFixed(2)}</td>
                  <td className="border border-gray-300 px-2 py-0.5 text-center font-bold uppercase">{r.status}</td>
                </tr>
              ))}
            </tbody>
          </table>
          {freeboard.zeroFreeboardQ !== null && (
            <p className="text-xs mt-2">Estimated Q at zero freeboard: <strong>{freeboard.zeroFreeboardQ.toFixed(0)}</strong> (interpolated)</p>
          )}
        </div>
      )}

      {/* Method Comparison */}
      {results && (
        <div className="break-before-page">
          <h2 className="text-lg font-bold border-b-2 border-blue-600 pb-1 mb-4" style={{ fontFamily: 'Georgia, serif' }}>Method Comparison</h2>
          {([
            { title: 'Upstream WSEL', getValue: (r: typeof results.energy[0]) => r.upstreamWsel.toFixed(2) },
            { title: 'Head Loss', getValue: (r: typeof results.energy[0]) => r.totalHeadLoss.toFixed(3) },
            { title: 'Approach Velocity', getValue: (r: typeof results.energy[0]) => r.approachVelocity.toFixed(2) },
            { title: 'Froude Number', getValue: (r: typeof results.energy[0]) => r.froudeApproach.toFixed(3) },
          ] as const).map(({ title, getValue }) => (
            <div key={title} className="mb-4">
              <h3 className="text-xs font-bold uppercase text-gray-500 mb-1">{title}</h3>
              <table className="w-full text-xs border-collapse">
                <thead>
                  <tr className="bg-gray-100">
                    <th className="border border-gray-300 px-2 py-1 text-left">Method</th>
                    {profiles.map(p => <th key={p.name} className="border border-gray-300 px-2 py-1 text-right">{p.name}</th>)}
                  </tr>
                </thead>
                <tbody>
                  {methods.map(m => (
                    <tr key={m}>
                      <td className="border border-gray-300 px-2 py-0.5 capitalize">{m === 'wspro' ? 'WSPRO' : m}</td>
                      {results[m].map((r, i) => (
                        <td key={i} className="border border-gray-300 px-2 py-0.5 text-right font-mono">{r.error ? 'ERR' : getValue(r)}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ))}
        </div>
      )}

      {/* Footer */}
      <div className="text-center text-xs text-gray-400 mt-16 pt-4 border-t border-gray-200">
        Generated by Bridge Loss Calculator
      </div>
    </div>
  );
}
