'use client';

import { ReactNode, useEffect, useState } from 'react';
import { useProjectStore } from '@/store/project-store';
import { computeFreeboard } from '@/engine/freeboard';

/* ─── Constants ─── */

const FONT = "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif";
const METHODS = ['energy', 'momentum', 'yarnell', 'wspro'] as const;
const METHOD_LABELS: Record<string, string> = {
  energy: 'Energy',
  momentum: 'Momentum',
  yarnell: 'Yarnell',
  wspro: 'WSPRO',
};

/** Max cross-section rows per page (leaves room for header + table header + footer). */
const XS_ROWS_PER_PAGE = 38;

/* ─── Page template ─── */

function PageHeader({ section, reportTitle }: { section: string; reportTitle: string }) {
  return (
    <div className="flex items-baseline justify-between border-b border-gray-300 pb-1 mb-3">
      <span className="text-[10px] text-gray-400 font-medium tracking-wide uppercase">{reportTitle}</span>
      <span className="text-[10px] text-gray-500 font-semibold">{section}</span>
    </div>
  );
}

function PageFooter({ page, date }: { page: number; date: string }) {
  return (
    <div className="print-page-footer flex items-center justify-between border-t border-gray-200 pt-1">
      <span className="text-[9px] text-gray-300">Generated by Bridge Loss Calculator &middot; QA verification only</span>
      <span className="text-[9px] text-gray-400">{date} &middot; Page {page}</span>
    </div>
  );
}

function Page({ section, page, date, reportTitle, children }: {
  section: string;
  page: number;
  date: string;
  reportTitle: string;
  children: ReactNode;
}) {
  return (
    <div className="print-page">
      <PageHeader section={section} reportTitle={reportTitle} />
      <div className="print-page-content">
        {children}
      </div>
      <PageFooter page={page} date={date} />
    </div>
  );
}

/* ─── Shared table helpers ─── */

const TH = "border border-gray-200 px-1.5 py-0.5 text-left font-medium text-[10px]";
const TH_R = "border border-gray-200 px-1.5 py-0.5 text-right font-medium text-[10px]";
const TH_C = "border border-gray-200 px-1.5 py-0.5 text-center font-medium text-[10px]";
const TD = "border border-gray-200 px-1.5 py-[2px] text-[10px]";
const TD_N = "border border-gray-200 px-1.5 py-[2px] text-[10px] tabular-nums";
const TD_NR = "border border-gray-200 px-1.5 py-[2px] text-[10px] tabular-nums text-right";

function SectionTitle({ number, title }: { number: number; title: string }) {
  return <h2 className="text-[12px] font-semibold text-gray-800 mb-0.5">{number}. {title}</h2>;
}

function SectionDesc({ children }: { children: ReactNode }) {
  return <p className="text-[9px] text-gray-400 mb-2 max-w-[140mm] leading-snug">{children}</p>;
}

function PrintBullets({ items, className = 'text-gray-500' }: { items: string | string[]; className?: string }) {
  const list = Array.isArray(items) ? items : [items];
  return (
    <ul className="max-w-[160mm] space-y-0.5">
      {list.map((item, i) => (
        <li key={i} className={`text-[10px] leading-snug flex items-baseline gap-1.5 ${className}`}>
          <span className="text-gray-300 shrink-0">•</span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}

/* ─── Report ─── */

export function PrintReport() {
  const crossSection = useProjectStore((s) => s.crossSection);
  const bridge = useProjectStore((s) => s.bridgeGeometry);
  const profiles = useProjectStore((s) => s.flowProfiles);
  const coefficients = useProjectStore((s) => s.coefficients);
  const results = useProjectStore((s) => s.results);
  const projectName = useProjectStore((s) => s.projectName);
  const aiSummary = useProjectStore((s) => s.aiSummary);
  const aiSummaryLoading = useProjectStore((s) => s.aiSummaryLoading);

  const methods = ['energy', 'momentum', 'yarnell', 'wspro'] as const;
  const freeboard = results ? computeFreeboard(results, bridge, profiles, coefficients.freeboardThreshold) : null;
  const date = new Date().toLocaleDateString('en-AU', { year: 'numeric', month: 'long', day: 'numeric' });
  const title = projectName || 'Bridge Hydraulic Loss Assessment';

  // Capture live chart SVGs before print so they appear in the report
  const [chartSvgs, setChartSvgs] = useState<{ label: string; svg: string; width: number; height: number }[]>([]);

  useEffect(() => {
    function captureCharts() {
      const svgs: typeof chartSvgs = [];
      // Find all rendered SVGs inside known chart containers
      const chartContainers = document.querySelectorAll<HTMLDivElement>(
        // Cross-section charts, afflux charts, WSEL charts
        '[class*="h-[300px]"], [class*="h-[350px]"], [class*="h-[320px]"]'
      );
      chartContainers.forEach((container) => {
        const svg = container.querySelector('svg');
        if (!svg) return;
        // Determine label from nearest card title
        const card = container.closest('[class*="CardContent"]')?.parentElement;
        const titleEl = card?.querySelector('[class*="CardTitle"]');
        const label = titleEl?.textContent || 'Chart';
        svgs.push({
          label,
          svg: svg.outerHTML,
          width: svg.clientWidth || 600,
          height: svg.clientHeight || 300,
        });
      });
      setChartSvgs(svgs);
    }

    window.addEventListener('beforeprint', captureCharts);
    return () => window.removeEventListener('beforeprint', captureCharts);
  }, []);

  // Paginate cross-section rows
  const xsChunks: typeof crossSection[] = [];
  for (let i = 0; i < crossSection.length; i += XS_ROWS_PER_PAGE) {
    xsChunks.push(crossSection.slice(i, i + XS_ROWS_PER_PAGE));
  }

  let pageNum = 0;
  const nextPage = () => ++pageNum;

  return (
    <div className="print-report bg-white text-black text-[11px] leading-snug"
      style={{ fontFamily: FONT, display: 'none' }}>

      {/* ═══ PAGE: Cover ═══ */}
      <Page section="" page={nextPage()} date={date} reportTitle="">
        <div className="flex flex-col items-center justify-center h-full text-center">
          <div className="w-16 h-0.5 bg-blue-600 mb-6" />
          <h1 className="text-2xl font-semibold tracking-tight text-gray-900">Bridge Hydraulic Loss Assessment</h1>
          {projectName && <h2 className="text-base font-normal text-gray-500 mt-1">{projectName}</h2>}
          <div className="w-16 h-0.5 bg-blue-600 mt-6 mb-8" />
          <p className="text-xs text-gray-400">{date}</p>
        </div>
      </Page>

      {/* ═══ PAGE: Input Summary (geometry + profiles) ═══ */}
      <Page section="Input Summary" page={nextPage()} date={date} reportTitle={title}>
        <SectionTitle number={1} title="Input Summary" />
        <SectionDesc>
          Summary of bridge geometry, coefficients, and flow profiles used as inputs. Cross-section data is on the following page(s).
        </SectionDesc>

        {/* Bridge Geometry */}
        <h3 className="text-[11px] font-semibold mt-2 mb-1 text-gray-700">Bridge Geometry</h3>
        <p className="text-[9px] text-gray-400 mb-1">Structural dimensions of the bridge opening.</p>
        <div className="grid grid-cols-3 gap-x-4 gap-y-0.5 text-[10px] mb-3">
          <div><span className="text-gray-500">Low Chord Left:</span> <span className="tabular-nums font-medium">{bridge.lowChordLeft}</span></div>
          <div><span className="text-gray-500">Low Chord Right:</span> <span className="tabular-nums font-medium">{bridge.lowChordRight}</span></div>
          <div><span className="text-gray-500">High Chord:</span> <span className="tabular-nums font-medium">{bridge.highChord}</span></div>
          <div><span className="text-gray-500">Skew Angle:</span> <span className="tabular-nums font-medium">{bridge.skewAngle}&deg;</span></div>
          <div><span className="text-gray-500">Left Abutment:</span> <span className="tabular-nums font-medium">{bridge.leftAbutmentStation}</span></div>
          <div><span className="text-gray-500">Right Abutment:</span> <span className="tabular-nums font-medium">{bridge.rightAbutmentStation}</span></div>
          <div><span className="text-gray-500">Piers:</span> <span className="tabular-nums font-medium">{bridge.piers.length}</span></div>
          {coefficients.debrisBlockagePct > 0 && (
            <div><span className="text-gray-500">Debris Blockage:</span> <span className="tabular-nums font-medium">{coefficients.debrisBlockagePct}%</span></div>
          )}
        </div>

        {/* Coefficients summary */}
        <h3 className="text-[11px] font-semibold mt-2 mb-1 text-gray-700">Coefficients</h3>
        <p className="text-[9px] text-gray-400 mb-1">Loss coefficients and adjustment factors applied to all methods.</p>
        <div className="grid grid-cols-3 gap-x-4 gap-y-0.5 text-[10px] mb-3">
          <div><span className="text-gray-500">Contraction Coeff:</span> <span className="tabular-nums font-medium">{coefficients.contractionCoeff}</span></div>
          <div><span className="text-gray-500">Expansion Coeff:</span> <span className="tabular-nums font-medium">{coefficients.expansionCoeff}</span></div>
          {coefficients.yarnellK !== null && (
            <div><span className="text-gray-500">Yarnell K:</span> <span className="tabular-nums font-medium">{coefficients.yarnellK}</span></div>
          )}
          <div><span className="text-gray-500">Max Iterations:</span> <span className="tabular-nums font-medium">{coefficients.maxIterations}</span></div>
          <div><span className="text-gray-500">Tolerance:</span> <span className="tabular-nums font-medium">{coefficients.tolerance}</span></div>
          {coefficients.debrisBlockagePct > 0 && (
            <div><span className="text-gray-500">Debris Blockage:</span> <span className="tabular-nums font-medium">{coefficients.debrisBlockagePct}%</span></div>
          )}
          {coefficients.manningsNSensitivityPct !== null && coefficients.manningsNSensitivityPct > 0 && (
            <div><span className="text-gray-500">Manning&apos;s n Sensitivity:</span> <span className="tabular-nums font-medium">&plusmn;{coefficients.manningsNSensitivityPct}%</span></div>
          )}
        </div>

        {/* Flow Profiles */}
        <h3 className="text-[11px] font-semibold mt-3 mb-1 text-gray-700">Flow Profiles</h3>
        <p className="text-[9px] text-gray-400 mb-1">Design flow scenarios with downstream boundary conditions.</p>
        <table className="w-full text-[10px] border-collapse mb-3">
          <thead>
            <tr className="bg-gray-50">
              <th className={TH}>Name</th>
              <th className={TH}>ARI</th>
              <th className={TH_R}>Q</th>
              <th className={TH_R}>DS WSEL</th>
              <th className={TH_R}>Slope</th>
            </tr>
          </thead>
          <tbody>
            {profiles.map((p, i) => (
              <tr key={i} className={i % 2 ? 'bg-gray-50/50' : ''}>
                <td className={TD}>{p.name}</td>
                <td className={TD}>{p.ari || '—'}</td>
                <td className={TD_NR}>{p.discharge}</td>
                <td className={TD_NR}>{p.dsWsel}</td>
                <td className={TD_NR}>{p.channelSlope}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Page>

      {/* ═══ PAGE(s): Cross-Section Data ═══ */}
      {xsChunks.map((chunk, ci) => (
        <Page key={ci} section="Cross-Section Data" page={nextPage()} date={date} reportTitle={title}>
          {ci === 0 && (
            <>
              <SectionTitle number={2} title="Cross-Section Data" />
              <SectionDesc>
                Surveyed channel stations, elevations, and roughness coefficients defining the waterway geometry
                ({crossSection.length} points{xsChunks.length > 1 ? `, page ${ci + 1} of ${xsChunks.length}` : ''}).
              </SectionDesc>
            </>
          )}
          {ci > 0 && (
            <p className="text-[9px] text-gray-400 mb-2">Cross-section data continued (page {ci + 1} of {xsChunks.length})</p>
          )}
          <table className="w-full text-[10px] border-collapse">
            <thead>
              <tr className="bg-gray-50">
                <th className={TH}>Station</th>
                <th className={TH}>Elevation</th>
                <th className={TH}>Manning&apos;s n</th>
                <th className={TH}>Bank</th>
              </tr>
            </thead>
            <tbody>
              {chunk.map((p, i) => (
                <tr key={i} className={i % 2 ? 'bg-gray-50/50' : ''}>
                  <td className={TD_N}>{p.station.toFixed(1)}</td>
                  <td className={TD_N}>{p.elevation.toFixed(2)}</td>
                  <td className={TD_N}>{p.manningsN}</td>
                  <td className={TD}>{p.bankStation ?? '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Page>
      ))}

      {/* ═══ PAGE: Results — Freeboard & Regime ═══ */}
      {results && (
        <Page section="Results" page={nextPage()} date={date} reportTitle={title}>
          <SectionTitle number={3} title="Freeboard Check" />
          <SectionDesc>
            Clearance between computed upstream WSEL (Energy method) and bridge low chord.
            Positive = clearance below deck. Negative = pressure flow or overtopping.
          </SectionDesc>

          {freeboard && (
            <>
              <table className="w-full text-[10px] border-collapse mb-2">
                <thead>
                  <tr className="bg-gray-50">
                    <th className={TH}>Profile</th>
                    <th className={TH}>ARI</th>
                    <th className={TH_R}>Q</th>
                    <th className={TH_R}>US WSEL</th>
                    <th className={TH_R}>Low Chord</th>
                    <th className={TH_R}>Freeboard</th>
                    <th className={TH_C}>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {freeboard.profiles.map((r, i) => (
                    <tr key={i} className={i % 2 ? 'bg-gray-50/50' : ''}>
                      <td className={TD}>{r.profileName}</td>
                      <td className={TD}>{r.ari || '—'}</td>
                      <td className={TD_NR}>{r.discharge.toFixed(0)}</td>
                      <td className={TD_NR}>{r.usWsel.toFixed(2)}</td>
                      <td className={TD_NR}>{r.lowChord.toFixed(2)}</td>
                      <td className={TD_NR}>{r.freeboard.toFixed(2)}</td>
                      <td className={`${TD} text-center font-semibold uppercase ${r.status === 'clear' ? 'text-green-700' : r.status === 'low' ? 'text-amber-600' : 'text-red-600'}`}>
                        {r.status}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              {freeboard.zeroFreeboardQ !== null && (
                <p className="text-[9px] text-gray-500 mb-3">
                  Estimated Q at zero freeboard: <span className="font-semibold text-gray-700">{freeboard.zeroFreeboardQ.toFixed(0)}</span> (interpolated)
                </p>
              )}
            </>
          )}

          {/* Flow Regime */}
          <SectionTitle number={4} title="Flow Regime" />
          <SectionDesc>
            Classification per method per profile. Yarnell is valid for free-surface flow only — results
            under pressure (P) or overtopping (O) should be treated with caution.
          </SectionDesc>
          <table className="w-full text-[10px] border-collapse mb-1">
            <thead>
              <tr className="bg-gray-50">
                <th className={TH}>Method</th>
                {profiles.map(p => <th key={p.name} className={TH_C}>{p.name}</th>)}
              </tr>
            </thead>
            <tbody>
              {METHODS.map((m, mi) => (
                <tr key={m} className={mi % 2 ? 'bg-gray-50/50' : ''}>
                  <td className={`${TD} font-medium`}>{METHOD_LABELS[m]}</td>
                  {results[m].map((r, i) => {
                    const label = r.flowRegime === 'free-surface' ? 'F' : r.flowRegime === 'pressure' ? 'P' : 'O';
                    const warn = m === 'yarnell' && r.flowRegime !== 'free-surface';
                    return (
                      <td key={i} className={`${TD} text-center ${warn ? 'text-amber-600 font-semibold' : ''}`}>
                        {label}{warn ? ' ⚠' : ''}
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
          <div className="text-[9px] text-gray-400">
            F = Free Surface &nbsp;&middot;&nbsp; P = Pressure &nbsp;&middot;&nbsp; O = Overtopping
          </div>
        </Page>
      )}

      {/* ═══ PAGE: Method Comparison ═══ */}
      {results && (
        <Page section="Method Comparison" page={nextPage()} date={date} reportTitle={title}>
          <SectionTitle number={5} title="Method Comparison" />
          <SectionDesc>
            Four independent methods compared across flow profiles. Consistent results increase confidence;
            divergence beyond 10% warrants investigation.
          </SectionDesc>

          {([
            { title: 'Upstream WSEL', desc: 'Water surface elevation immediately upstream of the bridge.', getValue: (r: typeof results.energy[0]) => r.upstreamWsel.toFixed(2) },
            { title: 'Head Loss (Afflux)', desc: 'Total energy loss caused by the bridge constriction.', getValue: (r: typeof results.energy[0]) => r.totalHeadLoss.toFixed(3) },
            { title: 'Approach Velocity', desc: 'Mean velocity in the approach section.', getValue: (r: typeof results.energy[0]) => r.approachVelocity.toFixed(2) },
            { title: 'Froude Number', desc: 'Values above 1.0 indicate supercritical flow.', getValue: (r: typeof results.energy[0]) => r.froudeApproach.toFixed(3) },
          ] as const).map(({ title: t, desc, getValue }) => (
            <div key={t} className="mb-2.5">
              <h3 className="text-[10px] font-semibold text-gray-600 mb-0.5">{t}</h3>
              <p className="text-[9px] text-gray-400 mb-0.5">{desc}</p>
              <table className="w-full text-[10px] border-collapse">
                <thead>
                  <tr className="bg-gray-50">
                    <th className={TH}>Method</th>
                    {profiles.map(p => <th key={p.name} className={TH_R}>{p.name}</th>)}
                  </tr>
                </thead>
                <tbody>
                  {METHODS.map((m, mi) => (
                    <tr key={m} className={mi % 2 ? 'bg-gray-50/50' : ''}>
                      <td className={`${TD} font-medium`}>{METHOD_LABELS[m]}</td>
                      {results[m].map((r, i) => (
                        <td key={i} className={`${TD_NR} ${r.error ? 'text-red-500 italic' : ''}`}>
                          {r.error ? 'ERR' : getValue(r)}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ))}
        </Page>
      )}

      {/* ═══ PAGE(s): Charts ═══ */}
      {chartSvgs.length > 0 && (
        <Page section="Charts" page={nextPage()} date={date} reportTitle={title}>
          <SectionTitle number={6} title="Charts" />
          <SectionDesc>
            Captured from the interactive summary view. Cross-section profile, afflux rating curve, and upstream WSEL trend.
          </SectionDesc>
          {chartSvgs.map((chart, i) => (
            <div key={i} className="mb-4">
              <h3 className="text-[10px] font-semibold text-gray-600 mb-1">{chart.label}</h3>
              <div
                className="border border-gray-200 rounded overflow-hidden bg-white"
                style={{ maxWidth: '100%' }}
                dangerouslySetInnerHTML={{ __html: chart.svg }}
              />
            </div>
          ))}
        </Page>
      )}

      {/* ═══ PAGE: AI Analysis ═══ */}
      {(aiSummary || aiSummaryLoading) && results && (
        <Page section="AI Analysis" page={nextPage()} date={date} reportTitle={title}>
          <SectionTitle number={chartSvgs.length > 0 ? 7 : 6} title="AI Analysis" />
          <SectionDesc>
            Automated review of calculation results by AI. This analysis is supplementary —
            engineering judgement should always take precedence.
          </SectionDesc>

          {aiSummaryLoading ? (
            <p className="text-[10px] text-gray-400 italic mt-2">AI analysis pending…</p>
          ) : aiSummary ? (
            <div className="space-y-3 mt-2">
              <div>
                <h3 className="text-[11px] font-semibold text-gray-700 mb-1">Summary</h3>
                <PrintBullets items={aiSummary.overall} className="text-gray-600" />
              </div>

              {aiSummary.callouts.regime && (
                <div>
                  <h3 className="text-[10px] font-semibold text-gray-600 mb-0.5">Flow Regime</h3>
                  <PrintBullets items={aiSummary.callouts.regime} />
                </div>
              )}

              {aiSummary.callouts.freeboard && (
                <div>
                  <h3 className="text-[10px] font-semibold text-gray-600 mb-0.5">Freeboard</h3>
                  <PrintBullets items={aiSummary.callouts.freeboard} />
                </div>
              )}

              {aiSummary.callouts.comparison && (
                <div>
                  <h3 className="text-[10px] font-semibold text-gray-600 mb-0.5">Method Comparison</h3>
                  <PrintBullets items={aiSummary.callouts.comparison} />
                </div>
              )}

              {aiSummary.callouts.afflux && (
                <div>
                  <h3 className="text-[10px] font-semibold text-gray-600 mb-0.5">Afflux Trends</h3>
                  <PrintBullets items={aiSummary.callouts.afflux} />
                </div>
              )}

              {aiSummary.callouts.hecras && (
                <div>
                  <h3 className="text-[10px] font-semibold text-gray-600 mb-0.5">HEC-RAS Comparison</h3>
                  <PrintBullets items={aiSummary.callouts.hecras} />
                </div>
              )}

              <p className="text-[8px] text-gray-300 italic mt-4">
                Generated by GPT-5.4. This analysis is for reference only and does not constitute engineering advice.
              </p>
            </div>
          ) : null}
        </Page>
      )}

    </div>
  );
}
